#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaPresentacion
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="neptuno")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcategorias(categorias instance);
    partial void Updatecategorias(categorias instance);
    partial void Deletecategorias(categorias instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["neptunoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categorias> categorias
		{
			get
			{
				return this.GetTable<categorias>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_create")]
		public int sp_create([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombrecategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcategoria, nombrecategoria, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delete")]
		public int sp_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_load")]
		public ISingleResult<sp_loadResult> sp_load()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_loadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_update")]
		public int sp_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string nombrecategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombrecategoria, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_read")]
		public ISingleResult<sp_readResult> sp_read([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_readResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categorias")]
	public partial class categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcategoria;
		
		private string _nombrecategoria;
		
		private string _descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcategoriaChanging(int value);
    partial void OnidcategoriaChanged();
    partial void OnnombrecategoriaChanging(string value);
    partial void OnnombrecategoriaChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public categorias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idcategoria
		{
			get
			{
				return this._idcategoria;
			}
			set
			{
				if ((this._idcategoria != value))
				{
					this.OnidcategoriaChanging(value);
					this.SendPropertyChanging();
					this._idcategoria = value;
					this.SendPropertyChanged("idcategoria");
					this.OnidcategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecategoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombrecategoria
		{
			get
			{
				return this._nombrecategoria;
			}
			set
			{
				if ((this._nombrecategoria != value))
				{
					this.OnnombrecategoriaChanging(value);
					this.SendPropertyChanging();
					this._nombrecategoria = value;
					this.SendPropertyChanged("nombrecategoria");
					this.OnnombrecategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_loadResult
	{
		
		private int _idcategoria;
		
		private string _nombrecategoria;
		
		private string _descripcion;
		
		public sp_loadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategoria", DbType="Int NOT NULL")]
		public int idcategoria
		{
			get
			{
				return this._idcategoria;
			}
			set
			{
				if ((this._idcategoria != value))
				{
					this._idcategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecategoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombrecategoria
		{
			get
			{
				return this._nombrecategoria;
			}
			set
			{
				if ((this._nombrecategoria != value))
				{
					this._nombrecategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class sp_readResult
	{
		
		private int _idcategoria;
		
		private string _nombrecategoria;
		
		private string _descripcion;
		
		public sp_readResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcategoria", DbType="Int NOT NULL")]
		public int idcategoria
		{
			get
			{
				return this._idcategoria;
			}
			set
			{
				if ((this._idcategoria != value))
				{
					this._idcategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrecategoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombrecategoria
		{
			get
			{
				return this._nombrecategoria;
			}
			set
			{
				if ((this._nombrecategoria != value))
				{
					this._nombrecategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
